### ISSUE TITLE
iOS 13 support

### ISSUE THREAD

**Issue by Dejal** [samuelclay/turntouch-ios#10]
I'm testing on iOS 13, and fixing problems as I find them. This issue is to track those changes, and will be left open until after iOS 13 has been released (it's a moving target!).

**Comment by Dejal** [comment]
Note, if you build this in Xcode before version 11, you'll need to temporarily comment out this line:

    settingsViewController.isModalInPresentation = true

**Comment by samuelclay** [comment]
Oooh I'm going to want to release this soon!

**Comment by Dejal** [comment]
I'm done with my work for the month, so go ahead at your convenience!

**Comment by Dejal** [comment]
I'm not aware of any more iOS 13 issues for Turn Touch, so please release it at your convenience. I'm closing this; if anything else turns up, it can be added as a new issue.
