### ISSUE TITLE
Turn action map from options to actions

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-ios#4]
Add a switch button that turns the actions into actual actions and hold to change.

**Comment by Dejal** [comment]
Hopefully this is close enough to what you had in mind!

**Comment by samuelclay** [comment]
I love it, now time for a widget. I'll write the ticket now

**Comment by samuelclay** [comment]
How about long press to change? Right now long pressing switches to the app, which is good for the physical remote but incorrect for the diamond.
